# LAB 01 - NumPy Library [1]

## #01 NumPy 시작하기

### 라이브러리 참조하기

In [11]:
# numpy 라이브러리를 np라는 이름으로 사용하도록 import
import numpy as np

###배열 생성하기

### 리스트를 통한 1차원(=1행으로 구성) 배열 만들기

In [12]:
# list를 파라미터로 전달하여 ndarray 객체 생성
arr = np.array([1,3,5,7,9])
print(type(arr))
arr

<class 'numpy.ndarray'>


array([1, 3, 5, 7, 9])

### 배열의 크기

#### `len()` 함수를 사용하여  배열의 크기를 확인할 수 있다.


In [14]:
arr = np.array([10,30,50,70,90])
size = len(arr)
print("배열의 원소는 %d개 입니다." % size)

배열의 원소는 5개 입니다.


In [17]:
mydata = np.array([5,10,15,20,25])

#인덱싱을 사용한 원소의 접근
print(mydata[0])
print(mydata[1])
print(mydata[3])

#슬라이싱을 위한 구간 추출
print(mydata[1:4])
print(mydata[-4:-1])

5
10
20
[10 15 20]
[10 15 20]


In [19]:
mydata = np.array([100,110,120,130,140])

for i,v in enumerate(mydata):
    print("%d번째 원소 >> %d" % (i,v))

0번째 원소 >> 100
1번째 원소 >> 110
2번째 원소 >> 120
3번째 원소 >> 130
4번째 원소 >> 140


In [21]:
mylist = [100, 3.14, True]
mylist

[100, 3.14, True]

In [22]:
myarr = np.array(mylist)
myarr

array([100.  ,   3.14,   1.  ])