In [2]:
# LAB 01- NumPy Library [1]

## #02. `ndarray` 주요 기능

### 라이브러리 참조하기

In [4]:
# numpy 라이브러리를 np라는 이름으로 사용하도록 import

import numpy as np

In [6]:
mylist1 = [100.12, 3.14, 1.5]
myarr1 = np.array(mylist1, dtype='int')
myarr1

array([100,   3,   1])

In [8]:
mylist2 = [1.2, 3, True, '4']
myarr2 = np.array(mylist2)
myarr2

array(['1.2', '3', 'True', '4'], dtype='<U32')

In [11]:
mylist3 = [10, 20, 30, 40, 50]
myarr3 = np.array(mylist3)
print(type(myarr3), myarr3)

mylist3_1 = list(myarr3)
print(type(mylist3_1), mylist3_1)

<class 'numpy.ndarray'> [10 20 30 40 50]
<class 'list'> [np.int64(10), np.int64(20), np.int64(30), np.int64(40), np.int64(50)]


In [13]:
arr1 = np.array([10,15,20,25,30])
arr2 = np.array([2,3,4,5,6])
print(arr1)
print(arr2)

[10 15 20 25 30]
[2 3 4 5 6]


In [16]:
a= arr1+arr2
a

array([12, 18, 24, 30, 36])

In [18]:
b= arr1 -arr2
b

array([ 8, 12, 16, 20, 24])

In [20]:
c = arr1*arr2
c

array([ 20,  45,  80, 125, 180])

In [22]:
d= arr1/arr2
d

array([5., 5., 5., 5., 5.])

In [24]:
arr1 = np.array([10,15,20,25,30])
arr2 = np.array([2,3,4,5,6])
print(arr1)
print(arr2)

[10 15 20 25 30]
[2 3 4 5 6]


In [26]:
a = np.add(arr1,arr2)
a

array([12, 18, 24, 30, 36])

In [30]:
b = np.subtract(arr1, arr2)
b

array([ 8, 12, 16, 20, 24])

In [32]:
c = np.multiply(arr1,arr2)
c

array([ 20,  45,  80, 125, 180])

In [34]:
d = np.divide(arr1,arr2)
d

array([5., 5., 5., 5., 5.])

In [36]:
# 철수의 1학년~4학년까지의 평균 점수
grade = np.array([82,77,91,88])
grade

array([82, 77, 91, 88])

In [37]:
# ->추출하고자 하는 원본과 같은 사이즈의 배열을 생성한다.
# -> 추출할 값은 True, 그렇지 않으면 False
bool_array = np.array([True, False, True, False])
bool_array

array([ True, False,  True, False])

In [39]:
# -> 조건에 맞는 항목만 1차 배열로 추출
result1 = grade[bool_array]
result1

array([82, 91])

In [41]:
# 80점이상은 원소만 추출하기
# ->조건을 명시하기 위해 배열의 이름이 조건식에 명시된다.
mypoint = np.array([82,77,91,88])
ge80 = mypoint[mypoint>=80]
ge80


array([82, 91, 88])

In [43]:
ge80le90 = mypoint[np.logical_and(mypoint >=80, mypoint <=90)]
ge80le90

array([82, 88])

In [47]:
gt_or_lt = mypoint[np.logical_or(mypoint<80, mypoint>90)]
gt_or_lt

array([77, 91])

In [49]:
exam = np.array([60, 83, 75, 92, 86])

#첫 번째 파라미터로 주어진 조건이 참일 경우 '합격',
# 그렇지 않을 경우 '불합격'

result = np.where(exam>=80, '합격', '불합격')
result

array(['불합격', '합격', '불합격', '합격', '합격'], dtype='<U3')

In [50]:
exam = np.array([60,85,51,79,94,88])

#학점을 부여하기 위한 점수의 구간을 설정하는 조건들을 리스트로 설정
conditions = [ (exam>=90), (exam >=80), (exam>70)]
                 #if         elif           elif

#조건에 따라 부여될 학점 
value = ['A','B', 'C']

#조건과 조건을 판단하기 위한 값을 지정함
# default는 조건에 맞는 값이 아닌 경우 사용됨
result = np.select(conditions,value,default='F')
result

array(['F', 'B', 'F', 'C', 'A', 'B'], dtype='<U1')