# LAB 01- Data Analysis Overview / NumPy Library[1]

## #3. 그 밖의 ndarray형태

###라이브러리 참조

In [3]:
import numpy as np

In [5]:
myarray = np.array([
    [98,72,80,64],
    [88,90,80,72],
    [92,88,82,76]
])

print(myarray)

print("차원크기:", myarray.ndim)
print("차원별 원소수:",myarray.shape)
print("원소의 데이터 타입:", myarray.dtype)

[[98 72 80 64]
 [88 90 80 72]
 [92 88 82 76]]
차원크기: 2
차원별 원소수: (3, 4)
원소의 데이터 타입: int64


In [ ]:
bool_array = np.array([
    [True, False, True, False],
    [True, True, True, False],
    [True, True, True, False]
])

result1 = myarray[bool_array]
result1

array([98, 80, 88, 90, 80, 92, 88, 82])

In [13]:
result2 =myarray[myarray >=80]
result2

array([98, 80, 88, 90, 80, 92, 88, 82])

In [9]:
result3 = myarray[np.logical_and(myarray>=80,myarray<=90)]
result3

array([80, 88, 90, 80, 88, 82])

In [11]:
result4=myarray[np.logical_or(myarray <80, myarray>90)]
result4

array([98, 72, 64, 72, 92, 76])

In [15]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.full([3,4],10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [22]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
np.random.rand(10)

array([0.49395162, 0.82864772, 0.49715255, 0.46047277, 0.23728421,
       0.06484383, 0.83019221, 0.24533667, 0.89284538, 0.8087829 ])

In [32]:
np.random.rand(4,3)

array([[0.05841101, 0.8540877 , 0.17286455],
       [0.37306289, 0.03472957, 0.87618283],
       [0.53775339, 0.19448235, 0.32639662],
       [0.78183168, 0.25516835, 0.78423911]])

In [35]:
np.random.randint(0,9,10)

array([1, 6, 3, 2, 6, 8, 7, 6, 2, 4], dtype=int32)

In [38]:
np.random.randint(0,9, (3,4))

array([[8, 2, 7, 8],
       [4, 7, 4, 6],
       [2, 0, 7, 7]], dtype=int32)

In [40]:
np.random.seed(1234)
np.random.normal(0,1,(4,3))

array([[ 0.47143516, -1.19097569,  1.43270697],
       [-0.3126519 , -0.72058873,  0.88716294],
       [ 0.85958841, -0.6365235 ,  0.01569637],
       [-2.24268495,  1.15003572,  0.99194602]])

In [42]:
np.random.randn(10)

array([ 0.19342138,  0.55343891,  1.31815155, -0.46930528,  0.67555409,
       -1.81702723, -0.18310854,  1.05896919, -0.39784023,  0.33743765])

In [43]:
np.random.randn(4,3)

array([[ 1.04757857,  1.04593826,  0.86371729],
       [-0.12209157,  0.12471295, -0.32279481],
       [ 0.84167471,  2.39096052,  0.07619959],
       [-0.56644593,  0.03614194, -2.0749776 ]])