# LAB 01 - NumPy Library [1]

## #04. ndarray 형태 변환

### 라이브러리 참조

In [2]:
import numpy as np

In [4]:
# 0~10 전까지 1씩 증가하는 원소를 갖는 배열 생성
arr1 = np.arange(10)
print("원본배열:",arr1)
print("원본배열의 데이터 타입:", arr1.dtype)

원본배열: [0 1 2 3 4 5 6 7 8 9]
원본배열의 데이터 타입: int64


In [6]:
arr2 = arr1.astype('float')
print("형변환 후의 배열:", arr2)
print("변환된 배열의 데이터 타입:", arr2.dtype)

형변환 후의 배열: [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
변환된 배열의 데이터 타입: float64


In [8]:
arr3 = arr1.astype('str')
print("형변환 후의 배열:", arr3)
print("변환된 배열의 데이터 타입:", arr3.dtype)

형변환 후의 배열: ['0' '1' '2' '3' '4' '5' '6' '7' '8' '9']
변환된 배열의 데이터 타입: <U21


In [10]:
# 10~20 전까지 1씩 증가하는 원소를 갖는 배열 생성
arr1 = np.arange(10,20)
print("원본배열:", arr1)
print("원본배열의 데이터 타입:", arr1.dtype)

원본배열: [10 11 12 13 14 15 16 17 18 19]
원본배열의 데이터 타입: int64


In [12]:
arr2 = np.asarray(arr1, dtype='float')
print("형변환 후의 배열:", arr2)
print("변환된 배열의 데이터 타이비:", arr2.dtype)

형변환 후의 배열: [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
변환된 배열의 데이터 타이비: float64


In [14]:
arr3 = np.asarray(arr1, dtype='str')
print("형변환 후의 배열:", arr3)
print("변환된 배열의 데이터 타입:", arr3.dtype)

형변환 후의 배열: ['10' '11' '12' '13' '14' '15' '16' '17' '18' '19']
변환된 배열의 데이터 타입: <U21


In [16]:
origin = np.arange(20)
origin

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [20]:
x = origin.reshape(4,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [23]:
origin = np.array([[0,1,2,3,4],
                   [5,6,7,8,9],
                   [10,11,12,13,14],
                   [15,16,17,18,19]])

origin

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [26]:
y = origin.reshape(20)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [28]:
rows, cols = origin.shape
rows,cols

(4, 5)

In [30]:
z = origin.reshape(rows * cols)
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [32]:
origin = np.array([[0,1,2,3],
                   [4,5,6,7,],
                   [8,9,10,11]])
origin

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
x = origin.reshape(-1,1)
x

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [36]:
y = origin.reshape(-1,2)
y

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [39]:
origin = np.arange(12)
origin

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [42]:
x = origin.reshape(1,-1)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [44]:
y = origin.reshape(2,-1)
y

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [45]:
# 원본 배열
origin = np.array([[ 0,1,2,3,4,5],
                   [6,7,8,9,10,11]])

print(origin)
 
 #1차 배열로 재배치
x = origin.reshape(-1)
x

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])